# Generated by Django 4.2.13 on 2024-05-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_employee_employee_id_alter_employee_password'),
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('benefits', models.ManyToManyField(to='benefits.benefits')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.employee')),
            ],
        ),
    ]
