# Generated by Django 4.2.13 on 2024-05-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBenefits',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('health_insurance', models.BooleanField(default=False)),
                ('dental_insurance', models.BooleanField(default=False)),
                ('vision_insurance', models.BooleanField(default=False)),
                ('life_insurance', models.BooleanField(default=False)),
                ('retirement_savings', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employee_benefits',
            },
        ),
    ]
