# Generated by Django 4.2.13 on 2024-05-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email_address', models.EmailField(max_length=100, unique=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee_status', models.CharField(choices=[('active', 'Active'), ('on leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=10)),
                ('employee_type', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('temporary', 'Temporary')], default='full-time', max_length=10)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
