# Generated by Django 4.2.13 on 2024-05-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_employee_employee_id_alter_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebenefits',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employeebenefits',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeebenefits',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employeebenefits',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enrollment.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeebenefits',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
