# Generated by Django 4.2.13 on 2024-05-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_employee_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeebenefits',
            table=None,
        ),
    ]
